language: node_js
node_js:
- 12.4.0
install:
- npm install newman
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
jobs:
  include:
- stage: "API smoke test"
      name: "DEV1"
      if: type != api OR env(TEST_JOB) == "dev1"
    - script: node_modules/.bin/newman run tests/API_contract_tests.postman_collection.json -e tests/DEV1.postman_environment.json --env-var "loginEmail=$DEV1_USER_EMAIL" --env-var "loginPw=$DEV1_USER_PASSWORD" --env-var "marketoClientId=$MARKETO_CLIENT_ID" --env-var "marketoClientSecret=$MARKETO_CLIENT_SECRET" --env-var "marketoApi=$MARKETO_MUNCHKIN_API" --env-var "clinicEmail=$DEV1_CLINIC_EMAIL" --env-var "clinicPw=$DEV1_CLINIC_PASSWORD"
      name: "QA1"
      if: type != api OR env(TEST_JOB) == "qa1"
    - script: node_modules/.bin/newman run tests/API_contract_tests.postman_collection.json -e tests/QA1.postman_environment.json --env-var "loginEmail=$QA1_USER_EMAIL" --env-var "loginPw=$QA1_USER_PASSWORD" --env-var "marketoClientId=$MARKETO_CLIENT_ID" --env-var "marketoClientSecret=$MARKETO_CLIENT_SECRET" --env-var "marketoApi=$MARKETO_MUNCHKIN_API" --env-var "clinicEmail=$QA1_CLINIC_EMAIL" --env-var "clinicPw=$QA1_CLINIC_PASSWORD"
      name: "QA2"
      if: type != api OR env(TEST_JOB) == "qa2"
    - script: node_modules/.bin/newman run tests/API_contract_tests.postman_collection.json -e tests/QA2.postman_environment.json --env-var "loginEmail=$QA2_USER_EMAIL" --env-var "loginPw=$QA2_USER_PASSWORD" --env-var "marketoClientId=$MARKETO_CLIENT_ID" --env-var "marketoClientSecret=$MARKETO_CLIENT_SECRET" --env-var "marketoApi=$MARKETO_MUNCHKIN_API" --env-var "clinicEmail=$QA2_CLINIC_EMAIL" --env-var "clinicPw=$QA2_CLINIC_PASSWORD"
      name: "PRODUCTION"
    - script: node_modules/.bin/newman run tests/API_contract_tests.postman_collection.json -e tests/PRODUCTION.postman_environment.json --env-var "loginEmail=$PRODUCTION_USER_EMAIL" --env-var "loginPw=$PRODUCTION_USER_PASSWORD" --env-var "clinicEmail=$PRODUCTION_CLINIC_EMAIL" --env-var "clinicPw=$PRODUCTION_CLINIC_PASSWORD" --env-var "marketoApi=$MARKETO_MUNCHKIN_API" --env-var "marketoClientId=$MARKETO_CLIENT_ID" --env-var "marketoClientSecret=$MARKETO_CLIENT_SECRET" --env-var "marketoEmailPw=$MARKETO_EMAIL_PASSWORD"
      if: type != api OR env(TEST_JOB) == "production"