{{- if .Values.ingress.service.https.enabled -}}
{{- $spec := .Values.ingress.gateway.https -}}
{{- $port := $spec.port | default "443" -}}
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: https
  namespace: '{{ .Release.Namespace }}'
spec:
  displayName: https
  sslConfig:
    secretRef:
      name: '{{ .Values.ingress.certificate.secretName }}'
      namespace: '{{ $.Release.Namespace }}'
    sniDomains:
{{- range $dnsName := $spec.dnsNames }}
    - '{{ $dnsName }}'
{{- end }}
  virtualHost:
    domains:
{{- range $dnsName := $spec.dnsNames -}}
{{ if eq $dnsName "*" }}
    - '*'
{{- else }}
    - '{{ if ne $port "443" -}}{{- printf "%s:%s" $dnsName $port -}} {{- else -}} {{ printf "%s" $dnsName -}}{{- end -}}'
{{- end -}}
{{- end }}
    routes:
    - matchers:
      - methods:
        - POST
        - GET
        prefix: /
      routeAction:
        single:
          kube:
            ref:
              name: apitests
              namespace: '{{ .Release.Namespace }}'
            port: 8080
{{- end -}}
