{{- if .Values.ingress.service.http.enabled -}}
{{- $spec := .Values.ingress.gateway.http -}}
{{- $port := $spec.port | default "80" -}}
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: http
  namespace: '{{ .Release.Namespace }}'
spec:
  displayName: http
  virtualHost:
    domains:
{{- range $dnsName := $spec.dnsNames -}}
{{ if eq $dnsName "*" }}
    - '*'
{{- else }}
    - '{{ if ne $port "80" -}}{{- printf "%s:%s" $dnsName $port -}} {{- else -}} {{ printf "%s" $dnsName -}}{{- end -}}'
{{- end -}}
{{- end }}
    routes:
    - matchers:
      - methods:
        - POST
        - GET
        prefix: /
      routeAction:
        single:
          kube:
            ref:
              name: apitests
              namespace: '{{ .Release.Namespace }}'
            port: {{ $port }}
{{- end -}}
