secret:
  enabled: false
  data_:
    API_USER_EMAIL: ""
    API_USER_PW: ""
configmap:
  enabled: true
  data:
    HUBOT_GITHUB_EVENT_NOTIFIER_TYPES: "commit_comment,create,delete,deployment,deployment_status,issue_comment,issues,page_build,pull_request_review_comment,pull_request,push,repository,release,status,ping,pull_request_review"
    HUBOT_SLACK_ACCOUNT: "Tidepool"
    HUBOT_SLACK_ROOMS: "tidebot,github-events"
    inputToRepoMap: |-
      "{\"shared\":\"cluster-shared\",\"qa1\":\"cluster-qa1\",\"dev\":\"cluster-qa1\",\"qa2\":\"cluster-qa2\",\"int\":\"cluster-integration\",\"integration\":\"cluster-integration\",\"prd\":\"cluster-production\",\"prod\":\"cluster-production\",\"production\":\"cluster-production\",\"test\":\"integration-test\",\"stg\":\"cluster-staging\",\"staging\":\"cluster-staging\"}"
    inputToEnvironmentMap: |-
      "{\"qa1\":\"qa1\",\"dev\":\"qa1\",\"qa2\":\"qa2\",\"int\":\"external\",\"integration\":\"external\",\"prd\":\"production\",\"prod\":\"production\",\"production\":\"production\",\"test\":\"integration-test\",\"stg\":\"staging\",\"staging\":\"staging\"}"
    serviceRepoToService: |-
      "{\"slack-tidebot\":\"tidebot\"}"
deployment:
  podAnnotations: {}
  image: tidepool/slack-tidebot:master-5783cd86c2ed10f6f107047c6d60944e4cdadc6b
  resources: {}
  securityContext: {}
  hpa:
    enabled: false
ingress:
  certificate:
    secretName: tls
  service:
    http:
      enabled: false
    https:
      enabled: false
  gateway:
    http:
      dnsNames: []
    https:
      dnsNames: []
